---
outputs:
- Reveal
title: R Markdown blog?
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Blogging with R Markdown

:wave: Welcome!

---

I'm Maëlle, I like R, blogging and science.

I am a proud R-Lady. :purple_heart:

{{% fragment %}}

:house: https://masalmon.eu

{{% /fragment %}}


---

# Why blog?

---

* Notes for future you

* Passion for sharing?

* Opportunities

---

`r hugodown::embed_tweet("1313179237487124486")`

---

Teaching this course is an opportunity I got from blogging but blogging is not a pyramid scheme :wink:

---

# Why create a blog?

What if I don't really want to blog regularly?

<!--html_preserve-->

- {{% fragment %}}Have a platform to share stuff when you need to.{{% /fragment %}}
- {{% fragment %}}Portfolio. In particular, imagine someone recommending you for a thing.{{% /fragment %}}

<!--/html_preserve-->
---

# Why create websites

Personal website... But also

* course website

* event website

* etc.

Useful skill!

---

# Why create YOUR website/blog

In the words of Alison Hill, [set your website intentions](https://alison.rbind.io/post/new-year-new-blogdown/#step-0-set-your-intentions)!

Also note your website needs and thus your website will change with time!

---

# What is a website?

* static: HTML, CSS, JS

* non static: more machinery on the server side

Online server somewhere.

---

# Why Rmd for blogging?

- {{% fragment %}}Data analysis with R{{% /fragment %}}
- {{% fragment %}}Blogging about R{{% /fragment %}}
- {{% fragment %}}R as an utility tool e.g. to generate text from structured data{{% /fragment %}}
- {{% fragment %}}knitr supports other languages...{{% /fragment %}}

---

# WHAT is a Rmd blog?

---

IMHO :smile_cat:

I'll list criteria so we have something to compare our adventures to.

---

# Tech part

<!--html_preserve-->

* {{% fragment %}}Easy way to update from Rmd without too much copy-pasting{{% /fragment %}}

* {{% fragment %}}Fits into your existing workflow or uses things you want to learn and invest time in{{% /fragment %}}

* {{% fragment %}}Code, syntax highlighting{{% /fragment %}}

* {{% fragment %}}Modern tooling (html5? mobile friendly?){{% /fragment %}}

<!--/html_preserve-->
---

# (Data) Science part

* {{% fragment %}}References from a .bib file{{% /fragment %}}

* {{% fragment %}}Easy way to cite posts?{{% /fragment %}}

* {{% fragment %}}Equations {{% /fragment %}}

* {{% fragment %}}Content. Blog about anything.{{% /fragment %}}

---

# Human part

* {{% fragment %}}Accessible. Alt text, contrast.{{% /fragment %}}

* {{% fragment %}}You OWN it. Content, URL (if possible, no commercial service, no employer).{{% /fragment %}}

* {{% fragment %}}Allows for interactions (social media? commenting?){{% /fragment %}}

* {{% fragment %}}Costs little to no money.{{% /fragment %}}

---

# Let's go

* {{% fragment %}}distill{{% /fragment %}}

* {{% fragment %}}Hugo&blogdown (&hugodown){{% /fragment %}}

* {{% fragment %}}Reproducibility{{% /fragment %}}

* {{% fragment %}}Promotion{{% /fragment %}}

* {{% fragment %}}Debrief{{% /fragment %}}

---

# We'll start with a tour of the course website

https://tiny.cc/rmd-blogging-blr
