---
outputs:
- Reveal
title: Conclusion
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Blogging with R Markdown

:sob: Nearly time to say goodbye!

---

* distill: perfect, not flexible. With postcard for a slick homepage.

* Hugo: very flexible (too flexible?), changes fast
    * with blogdown: complete R package, outdated docs, Markdown less easy to get.
    * with hugodown: minimal&experimental R package, Markdown first.

---

# What to choose

* distill with postcard

* Hugo, with more or less involvement with Hugo. 

---

# What to choose

Start by playing! Don't commit right away.

Does any of you want to say what they'd choose and why?

---

# True for all

* Read the docs and follow development! :eyes:

* Backup! :warning:

---

# Change your mind?

* Migration tools

* `yaml`, `commonmark` packages, etc.

* [Redirects](https://yihui.org/en/2017/11/301-redirect/)! URLs are important. 404 page.

---

# Have fun!

If you're worried about blogging, find a blogging buddy to read your drafts?

Make efforts but don't be perfectionist.

---

```{=markdown}
<script async class="speakerdeck-embed" data-id="5106edda6ee44324b5fdffd82e15d249" data-ratio="1.8" src="https://speakerdeck.com/assets/embed.js"></script>
```

---

# Setup is not fun

* With R helper packages, setup is smoother

* But in general setup = learning a new thing, hard but then you get used to it!

---

# A word of caution

What if you enjoy setup too much?

---

`r hugodown::embed_tweet("1332830570729058313")`

---

# Regular blogging?

No you don't have to unless you call your blog "the daily blog" or so. :wink:

Only write if you enjoy it! Your blog can be a portfolio/news board only.

---

# Thank you!

:pray: Y'all for joining!

:pray: R-Ladies Bangalore, in particular Adithi R. Upadhya, for organizing!

---

# Tell me

* Issues in the [website repo](https://github.com/maelle/rladies-blr-rmd-blogging/issues) for questions  :raising_hand:

* [Tweets](https://twitter.com/ma_salmon)/emails to show me your websites. :star:
